function ValObjectiveFun = objectif(FactToIdentify)

% function ErrorVector = objectif(FactToIdentify)


% format long
tic;
typerun=3;

% fOptimRmt=FactOptim(1);
% fOptimRvaor=FactOptim(2);
% fOptimRsys=FactOptim(3);
% fOptimRtc=FactOptim(4);
% fOptimRpv=FactOptim(5);
% fOptimRpul=FactOptim(6);
% fOptimCaor=FactOptim(7);
% fOptimCvc=FactOptim(8);
% fOptimCpa=FactOptim(9);
% fOptimCpu=FactOptim(10);
% fOptimSBV=FactOptim(11);
% fOptimVw_lv=FactOptim(12);
% fOptimVw_rv=FactOptim(13);
% fOptimf_PassiveForce=FactOptim(14);
FactOptim=ones(1,14);
j=1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%   BEGIN 9 params %%%%%%%
% FactOptim(1)=FactToIdentify(j);j=j+1; % fOptimRmt
% FactOptim(2)=FactToIdentify(j);j=j+1; % fOptimRvao
FactOptim(3)=FactToIdentify(j);j=j+1; % fOptimRsys

% FactOptim(4)=FactToIdentify(j);j=j+1; % fOptimRtc
% FactOptim(5)=FactToIdentify(j);j=j+1; % fOptimRpv
FactOptim(6)=FactToIdentify(j);j=j+1; % fOptimRpul

FactOptim(7)=FactToIdentify(j);j=j+1; % fOptimCaor
FactOptim(8)=FactToIdentify(j);j=j+1; % fOptimCvc
FactOptim(9)=FactToIdentify(j);j=j+1; % fOptimCpa
FactOptim(10)=FactToIdentify(j);j=j+1; % fOptimCpu

FactOptim(11)=FactToIdentify(j);j=j+1; % fOptimSBV

FactOptim(12)=FactToIdentify(j);j=j+1; % fOptimVw_lv
FactOptim(13)=FactToIdentify(j);j=j+1; % fOptimVw_rv

% FactOptim(14)=FactToIdentify(j);j=j+1; %fOptimf_PassiveForce
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%   END 9 params   %%%%%%%

% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%   BEGIN 3 params %%%%%%%
% FactOptim(1)=FactToIdentify(j);j=j+1; % fOptimRmt
% % FactOptim(2)=FactToIdentify(j);j=j+1; % fOptimRvao
% % FactOptim(3)=FactToIdentify(j);j=j+1; % fOptimRsys
% 
% FactOptim(4)=FactToIdentify(j);j=j+1; % fOptimRtc
% FactOptim(5)=FactToIdentify(j);j=j+1; % fOptimRpv
% % FactOptim(6)=FactToIdentify(j);j=j+1; % fOptimRpul
% % 
% % FactOptim(7)=FactToIdentify(j);j=j+1; % fOptimCaor
% % FactOptim(8)=FactToIdentify(j);j=j+1; % fOptimCvc
% % FactOptim(9)=FactToIdentify(j);j=j+1; % fOptimCpa
% % FactOptim(10)=FactToIdentify(j);j=j+1; % fOptimCpu
% % 
% % FactOptim(11)=FactToIdentify(j);j=j+1; % fOptimSBV
% % 
% % FactOptim(12)=FactToIdentify(j);j=j+1; % fOptimVw_lv
% % FactOptim(13)=FactToIdentify(j);j=j+1; % fOptimVw_rv
% 
% % FactOptim(14)=FactToIdentify(j);j=j+1; %fOptimf_PassiveForce
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%   END 3 params   %%%%%%%


longvectFact=length(FactToIdentify);
PrintToFile=[ ];

for i=1:longvectFact;
disp(sprintf('                         Value of the unknown n°: %d = %0.16e',i,FactToIdentify(i)));
PrintToFile=[PrintToFile FactToIdentify(i)];
end
CalculatedVals=NLD7ch_NewHeart_OPTIM(FactOptim,typerun)

j=1;
Plv_min =CalculatedVals(j);j=j+1;
Plv_max =CalculatedVals(j);j=j+1;
Plv_mean=CalculatedVals(j);j=j+1;
Plv_ampl=CalculatedVals(j);j=j+1;
Vlv_min =CalculatedVals(j);j=j+1;
SVlv    =CalculatedVals(j);j=j+1;
Pao_min =CalculatedVals(j);j=j+1;
Pao_max =CalculatedVals(j);j=j+1;
Pao_mean=CalculatedVals(j);j=j+1;
Pao_ampl=CalculatedVals(j);j=j+1;
Pvc_min =CalculatedVals(j);j=j+1; 
Pvc_max =CalculatedVals(j);j=j+1;
Pvc_mean=CalculatedVals(j);j=j+1; 
Pvc_ampl=CalculatedVals(j);j=j+1;
Prv_min =CalculatedVals(j);j=j+1;
Prv_max =CalculatedVals(j);j=j+1;
Prv_mean=CalculatedVals(j);j=j+1;
Prv_ampl=CalculatedVals(j);j=j+1;
Vrv_min =CalculatedVals(j);j=j+1;
SVrv    =CalculatedVals(j);j=j+1;
Ppa_min =CalculatedVals(j);j=j+1; 
Ppa_max =CalculatedVals(j);j=j+1; 
Ppa_mean=CalculatedVals(j);j=j+1; 
Ppa_ampl=CalculatedVals(j);j=j+1; 
Ppu_min =CalculatedVals(j);j=j+1;
Ppu_max =CalculatedVals(j);j=j+1; 
Ppu_mean=CalculatedVals(j);j=j+1;
Ppu_ampl=CalculatedVals(j);j=j+1; 
Qmt_max=CalculatedVals(j);j=j+1; 
Qvao_max=CalculatedVals(j);j=j+1; 
Qtc_max=CalculatedVals(j);j=j+1; 
Qpv_max=CalculatedVals(j);j=j+1; 
dtLvEjection=CalculatedVals(j);j=j+1; 

QmtRelQvao=Qmt_max/Qvao_max;
QtcRelQvao=Qtc_max/Qvao_max;
QpvRelQvao=Qpv_max/Qvao_max;

SV=0.5*(SVlv+SVrv);


SV_Wtd=60;

Plv_min_Wtd=4.34;
Plv_max_Wtd=130;
Plv_mean_Wtd=59;
Plv_ampl_Wtd=1e69;

Vlv_min_Wtd=60;

Pao_min_Wtd=88.17;
Pao_max_Wtd=123;
Pao_mean_Wtd=108;
Pao_ampl_Wtd=1e69;

Pvc_min_Wtd=4.5;%7;
Pvc_max_Wtd=6;%7;
Pvc_mean_Wtd=1e69;%7;
Pvc_ampl_Wtd=0.5;%1.;%1.5;

Prv_min_Wtd=1;
Prv_max_Wtd=25;
Prv_mean_Wtd=12;
Prv_ampl_Wtd=1e69;

Vrv_min_Wtd=60;

Ppa_min_Wtd=14;
Ppa_max_Wtd=22.5;
Ppa_mean_Wtd=19;
Ppa_ampl_Wtd=1e69;

Ppu_min_Wtd=12.5;%9.5;%7.5;%
Ppu_max_Wtd=14;%9.5;%7.5;%
Ppu_mean_Wtd=1e69;%9.5;%7.5;%
Ppu_ampl_Wtd=2;%

% QmtRelQvao_Wtd=1.162110241739171; 
% QtcRelQvao_Wtd=0.989364139421700; 
% QpvRelQvao_Wtd=0.826285654781760; 
% dtLvEjection_Wtd=254.4955792818479; 

QmtRelQvao_Wtd=1; 
QtcRelQvao_Wtd=0.8; 
QpvRelQvao_Wtd=0.8; 
dtLvEjection_Wtd=254.4955792818479; 


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%   BEGIN 9 params %%%%%%%
Weights    =[...
1 ...%  6               SV_Wtd...
0 ...% 3                Plv_min_Wtd... 
0 ...% 3                Plv_max_Wtd... 
1 ...% 3                Plv_mean_Wtd... 
0 ...% 3                Plv_ampl_Wtd... 
1 ...%                 Vlv_min_Wtd... 
0 ...%                 Pao_min_Wtd... 
0 ...%                 Pao_max_Wtd... 
1 ...%                 Pao_mean_Wtd... 
0 ...%                 Pao_ampl_Wtd... 
0 ...%                 Pvc_min_Wtd... 
0 ...%                 Pvc_max_Wtd... 
0 ...%                 Pvc_mean_Wtd... 
1 ...%                 Pvc_ampl_Wtd... 
0 ...%                 Prv_min_Wtd... 
0 ...%                 Prv_max_Wtd... 
1 ...%                 Prv_mean_Wtd... 
0 ...%                 Prv_ampl_Wtd... 
1 ...%                 Vrv_min_Wtd... 
0 ...%                 Ppa_min_Wtd... 
0 ...%                 Ppa_max_Wtd... 
1 ...%                 Ppa_mean_Wtd... 
0 ...%                 Ppa_ampl_Wtd... 
0 ...%                 Ppu_min_Wtd... 
0 ...%                 Ppu_max_Wtd... 
0 ...%                 Ppu_mean_Wtd... 
1 ...%                 Ppu_ampl_Wtd... 
0 ...%                 QmtRelQvao 
0 ...%                 QtcRelQvao 
0 ...%                 QpvRelQvao 
0 ...%                 dtLvEjection 
                 ];      
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%   END 9 params %%%%%%%

% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%   BEGIN 3 params %%%%%%%
% Weights    =[...
% 0 ...%  6               SV_Wtd...
% 0 ...% 3                Plv_min_Wtd... 
% 0 ...% 3                Plv_max_Wtd... 
% 0 ...% 3                Plv_mean_Wtd... 
% 0 ...% 3                Plv_ampl_Wtd... 
% 0 ...%                 Vlv_min_Wtd... 
% 0 ...%                 Pao_min_Wtd... 
% 0 ...%                 Pao_max_Wtd... 
% 0 ...%                 Pao_mean_Wtd... 
% 0 ...%                 Pao_ampl_Wtd... 
% 0 ...%                 Pvc_min_Wtd... 
% 0 ...%                 Pvc_max_Wtd... 
% 0 ...%                 Pvc_mean_Wtd... 
% 0 ...%                 Pvc_ampl_Wtd... 
% 0 ...%                 Prv_min_Wtd... 
% 0 ...%                 Prv_max_Wtd... 
% 0 ...%                 Prv_mean_Wtd... 
% 0 ...%                 Prv_ampl_Wtd... 
% 0 ...%                 Vrv_min_Wtd... 
% 0 ...%                 Ppa_min_Wtd... 
% 0 ...%                 Ppa_max_Wtd... 
% 0 ...%                 Ppa_mean_Wtd... 
% 0 ...%                 Ppa_ampl_Wtd... 
% 0 ...%                 Ppu_min_Wtd... 
% 0 ...%                 Ppu_max_Wtd... 
% 0 ...%                 Ppu_mean_Wtd... 
% 0 ...%                 Ppu_ampl_Wtd... 
% 1 ...%                 QmtRelQvao 
% 1 ...%                 QtcRelQvao 
% 1 ...%                 QpvRelQvao 
% 0 ...%                 dtLvEjection 
%                  ];      
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%   END 3 params %%%%%%%

% % %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%   BEGIN 12 params %%%%%%%
% Weights    =[...
% 1 ...%  6               SV_Wtd...
% 0 ...% 3                Plv_min_Wtd... 
% 0 ...% 3                Plv_max_Wtd... 
% 1 ...% 3                Plv_mean_Wtd... 
% 0 ...% 3                Plv_ampl_Wtd... 
% 1 ...%                 Vlv_min_Wtd... 
% 0 ...%                 Pao_min_Wtd... 
% 0 ...%                 Pao_max_Wtd... 
% 1 ...%                 Pao_mean_Wtd... 
% 0 ...%                 Pao_ampl_Wtd... 
% 0 ...%                 Pvc_min_Wtd... 
% 0 ...%                 Pvc_max_Wtd... 
% 0 ...%                 Pvc_mean_Wtd... 
% 1 ...%                 Pvc_ampl_Wtd... 
% 0 ...%                 Prv_min_Wtd... 
% 0 ...%                 Prv_max_Wtd... 
% 1 ...%                 Prv_mean_Wtd... 
% 0 ...%                 Prv_ampl_Wtd... 
% 1 ...%                 Vrv_min_Wtd... 
% 0 ...%                 Ppa_min_Wtd... 
% 0 ...%                 Ppa_max_Wtd... 
% 1 ...%                 Ppa_mean_Wtd... 
% 0 ...%                 Ppa_ampl_Wtd... 
% 0 ...%                 Ppu_min_Wtd... 
% 0 ...%                 Ppu_max_Wtd... 
% 0 ...%                 Ppu_mean_Wtd... 
% 1 ...%                 Ppu_ampl_Wtd... 
% 1 ...%                 QmtRelQvao 
% 1 ...%                 QtcRelQvao 
% 1 ...%                 QpvRelQvao 
% 0 ...%                 dtLvEjection 
%                  ];      
% % %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%   END 12 params %%%%%%%

             
             
CalculatedVals=[...
                SV...         
                Plv_min...     
                Plv_max...     
                Plv_mean...     
                Plv_ampl... 
                Vlv_min... 
                Pao_min...     
                Pao_max...     
                Pao_mean...     
                Pao_ampl... 
                Pvc_min...     
                Pvc_max...     
                Pvc_mean...     
                Pvc_ampl...                  
                Prv_min...     
                Prv_max...     
                Prv_mean...     
                Prv_ampl...   
                Vrv_min...    
                Ppa_min...     
                Ppa_max...     
                Ppa_mean...     
                Ppa_ampl...     
                Ppu_min...     
                Ppu_max...     
                Ppu_mean...     
                Ppu_ampl...     
                QmtRelQvao...     
                QtcRelQvao...     
                QpvRelQvao...     
                dtLvEjection...     
                ];



            
            
            
WantedVals    =[...
                SV_Wtd...         
                Plv_min_Wtd...     
                Plv_max_Wtd...     
                Plv_mean_Wtd...     
                Plv_ampl_Wtd... 
                Vlv_min_Wtd... 
                Pao_min_Wtd...     
                Pao_max_Wtd...     
                Pao_mean_Wtd...     
                Pao_ampl_Wtd... 
                Pvc_min_Wtd...     
                Pvc_max_Wtd...     
                Pvc_mean_Wtd...     
                Pvc_ampl_Wtd...                  
                Prv_min_Wtd...     
                Prv_max_Wtd...     
                Prv_mean_Wtd...     
                Prv_ampl_Wtd...   
                Vrv_min_Wtd...    
                Ppa_min_Wtd...     
                Ppa_max_Wtd...     
                Ppa_mean_Wtd...     
                Ppa_ampl_Wtd...     
                Ppu_min_Wtd...     
                Ppu_max_Wtd...     
                Ppu_mean_Wtd...     
                Ppu_ampl_Wtd...     
                QmtRelQvao_Wtd...     
                QtcRelQvao_Wtd...     
                QpvRelQvao_Wtd...     
                dtLvEjection_Wtd...     
                ];      

PrintToFile=[PrintToFile CalculatedVals];
% longvectVals=length(WantedVals);
RefVals=WantedVals;
ErrorVector=(WantedVals - CalculatedVals)./RefVals;
AbsErrorVector=abs((WantedVals - CalculatedVals)./RefVals);
% ValObjectiveFun = (Weights*AbsErrorVector')/sum(Weights);  
%ValObjectiveFun = max(Weights.*AbsErrorVector);  

ValObjectiveFun = norm(Weights.*AbsErrorVector);

disp(sprintf('  Value of the obj.fct for corresp. vals of unknowns: %0.16e', ValObjectiveFun));
disp(sprintf('------------------------------------------------------'));

PrintToFile=[PrintToFile ValObjectiveFun];
c=clock;
PrintToFile=[PrintToFile c];
c=toc;
PrintToFile=[PrintToFile c];

load IdRes
IdRes=[IdRes;...
    PrintToFile];
save IdRes IdRes;

end

